//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.16 at 09:44:55 AM EDT 
//


package citrite;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:schemas-citrite-net:pip:sfdc:val-calc-request:1}Request"/>
 *         &lt;element ref="{urn:schemas-citrite-net:pip:bre:validations:1}Validations"/>
 *         &lt;element ref="{urn:schemas-citrite-net:pip:bre:payout:1}Payout"/>
 *         &lt;element ref="{urn:schemas-citrite-net:pip:sfdc:val-calc-info:1}Info"/>
 *         &lt;element ref="{urn:schemas-citrite-net:pip:bre:enduser:1}EndUserData"/>
 *         &lt;element ref="{urn:schemas-citrite-net:pip:bre:characteristics:1}CharacteristicsData"/>
 *         &lt;element ref="{urn:schemas-citrite-net:pip:bre:productrelease:1}ProductReleaseData"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "request",
    "validations",
    "payout",
    "info",
    "endUserData",
    "characteristicsData",
    "productReleaseData"
})
@XmlRootElement(name = "BREObjectSFDC", namespace = "urn:schemas-citrite-net:pip:canonical:bre:1")
public class BREObjectSFDC {

    @XmlElement(name = "Request", namespace = "urn:schemas-citrite-net:pip:sfdc:val-calc-request:1", required = true, nillable = true)
    protected Request request;
    @XmlElement(name = "Validations", namespace = "urn:schemas-citrite-net:pip:bre:validations:1", required = true, nillable = true)
    protected Validations validations;
    @XmlElement(name = "Payout", namespace = "urn:schemas-citrite-net:pip:bre:payout:1", required = true, nillable = true)
    protected Payout payout;
    @XmlElement(name = "Info", namespace = "urn:schemas-citrite-net:pip:sfdc:val-calc-info:1", required = true)
    protected Info info;
    @XmlElement(name = "EndUserData", namespace = "urn:schemas-citrite-net:pip:bre:enduser:1", required = true)
    protected EndUserData endUserData;
    @XmlElement(name = "CharacteristicsData", namespace = "urn:schemas-citrite-net:pip:bre:characteristics:1", required = true)
    protected CharacteristicsData characteristicsData;
    @XmlElement(name = "ProductReleaseData", namespace = "urn:schemas-citrite-net:pip:bre:productrelease:1", required = true)
    protected ProductReleaseData productReleaseData;

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link Request }
     *     
     */
    public Request getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link Request }
     *     
     */
    public void setRequest(Request value) {
        this.request = value;
    }

    /**
     * Gets the value of the validations property.
     * 
     * @return
     *     possible object is
     *     {@link Validations }
     *     
     */
    public Validations getValidations() {
        return validations;
    }

    /**
     * Sets the value of the validations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Validations }
     *     
     */
    public void setValidations(Validations value) {
        this.validations = value;
    }

    /**
     * Gets the value of the payout property.
     * 
     * @return
     *     possible object is
     *     {@link Payout }
     *     
     */
    public Payout getPayout() {
        return payout;
    }

    /**
     * Sets the value of the payout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Payout }
     *     
     */
    public void setPayout(Payout value) {
        this.payout = value;
    }

    /**
     * Gets the value of the info property.
     * 
     * @return
     *     possible object is
     *     {@link Info }
     *     
     */
    public Info getInfo() {
        return info;
    }

    /**
     * Sets the value of the info property.
     * 
     * @param value
     *     allowed object is
     *     {@link Info }
     *     
     */
    public void setInfo(Info value) {
        this.info = value;
    }

    /**
     * Gets the value of the endUserData property.
     * 
     * @return
     *     possible object is
     *     {@link EndUserData }
     *     
     */
    public EndUserData getEndUserData() {
        return endUserData;
    }

    /**
     * Sets the value of the endUserData property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndUserData }
     *     
     */
    public void setEndUserData(EndUserData value) {
        this.endUserData = value;
    }

    /**
     * Gets the value of the characteristicsData property.
     * 
     * @return
     *     possible object is
     *     {@link CharacteristicsData }
     *     
     */
    public CharacteristicsData getCharacteristicsData() {
        return characteristicsData;
    }

    /**
     * Sets the value of the characteristicsData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CharacteristicsData }
     *     
     */
    public void setCharacteristicsData(CharacteristicsData value) {
        this.characteristicsData = value;
    }

    /**
     * Gets the value of the productReleaseData property.
     * 
     * @return
     *     possible object is
     *     {@link ProductReleaseData }
     *     
     */
    public ProductReleaseData getProductReleaseData() {
        return productReleaseData;
    }

    /**
     * Sets the value of the productReleaseData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductReleaseData }
     *     
     */
    public void setProductReleaseData(ProductReleaseData value) {
        this.productReleaseData = value;
    }

}
