//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.16 at 09:44:55 AM EDT 
//


package citrite;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="AggregatedIPData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="IPData" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="BumpCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                             &lt;element name="ProductLineID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                             &lt;element name="ProductLineName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ProductReleaseID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                             &lt;element name="ProductReleaseName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="SuiteID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                             &lt;element name="SuiteName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DetailIPData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="IPData" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="BumpCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                             &lt;element name="DateCreated" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *                             &lt;element name="IPID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                             &lt;element name="ProductLineID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                             &lt;element name="ProductReleaseID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                             &lt;element name="ProductReleaseName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="SuiteID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                             &lt;element name="SuiteName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "aggregatedIPData",
    "detailIPData"
})
@XmlRootElement(name = "EndUserData", namespace = "urn:schemas-citrite-net:pip:bre:enduser:1")
public class EndUserData {

    @XmlElement(name = "AggregatedIPData")
    protected EndUserData.AggregatedIPData aggregatedIPData;
    @XmlElement(name = "DetailIPData")
    protected EndUserData.DetailIPData detailIPData;

    /**
     * Gets the value of the aggregatedIPData property.
     * 
     * @return
     *     possible object is
     *     {@link EndUserData.AggregatedIPData }
     *     
     */
    public EndUserData.AggregatedIPData getAggregatedIPData() {
        return aggregatedIPData;
    }

    /**
     * Sets the value of the aggregatedIPData property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndUserData.AggregatedIPData }
     *     
     */
    public void setAggregatedIPData(EndUserData.AggregatedIPData value) {
        this.aggregatedIPData = value;
    }

    /**
     * Gets the value of the detailIPData property.
     * 
     * @return
     *     possible object is
     *     {@link EndUserData.DetailIPData }
     *     
     */
    public EndUserData.DetailIPData getDetailIPData() {
        return detailIPData;
    }

    /**
     * Sets the value of the detailIPData property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndUserData.DetailIPData }
     *     
     */
    public void setDetailIPData(EndUserData.DetailIPData value) {
        this.detailIPData = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="IPData" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="BumpCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="ProductLineID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="ProductLineName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="ProductReleaseID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="ProductReleaseName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="SuiteID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="SuiteName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ipData"
    })
    public static class AggregatedIPData {

        @XmlElement(name = "IPData")
        protected List<EndUserData.AggregatedIPData.IPData> ipData;

        /**
         * Gets the value of the ipData property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ipData property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIPData().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EndUserData.AggregatedIPData.IPData }
         * 
         * 
         */
        public List<EndUserData.AggregatedIPData.IPData> getIPData() {
            if (ipData == null) {
                ipData = new ArrayList<EndUserData.AggregatedIPData.IPData>();
            }
            return this.ipData;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="BumpCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="ProductLineID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="ProductLineName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ProductReleaseID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="ProductReleaseName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="SuiteID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="SuiteName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "bumpCount",
            "productLineID",
            "productLineName",
            "productReleaseID",
            "productReleaseName",
            "suiteID",
            "suiteName"
        })
        public static class IPData {

            @XmlElement(name = "BumpCount")
            protected Integer bumpCount;
            @XmlElement(name = "ProductLineID")
            protected Integer productLineID;
            @XmlElement(name = "ProductLineName")
            protected String productLineName;
            @XmlElement(name = "ProductReleaseID")
            protected Integer productReleaseID;
            @XmlElement(name = "ProductReleaseName")
            protected String productReleaseName;
            @XmlElement(name = "SuiteID")
            protected Integer suiteID;
            @XmlElement(name = "SuiteName")
            protected String suiteName;

            /**
             * Gets the value of the bumpCount property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getBumpCount() {
                return bumpCount;
            }

            /**
             * Sets the value of the bumpCount property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBumpCount(Integer value) {
                this.bumpCount = value;
            }

            /**
             * Gets the value of the productLineID property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getProductLineID() {
                return productLineID;
            }

            /**
             * Sets the value of the productLineID property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setProductLineID(Integer value) {
                this.productLineID = value;
            }

            /**
             * Gets the value of the productLineName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProductLineName() {
                return productLineName;
            }

            /**
             * Sets the value of the productLineName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProductLineName(String value) {
                this.productLineName = value;
            }

            /**
             * Gets the value of the productReleaseID property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getProductReleaseID() {
                return productReleaseID;
            }

            /**
             * Sets the value of the productReleaseID property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setProductReleaseID(Integer value) {
                this.productReleaseID = value;
            }

            /**
             * Gets the value of the productReleaseName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProductReleaseName() {
                return productReleaseName;
            }

            /**
             * Sets the value of the productReleaseName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProductReleaseName(String value) {
                this.productReleaseName = value;
            }

            /**
             * Gets the value of the suiteID property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getSuiteID() {
                return suiteID;
            }

            /**
             * Sets the value of the suiteID property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setSuiteID(Integer value) {
                this.suiteID = value;
            }

            /**
             * Gets the value of the suiteName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSuiteName() {
                return suiteName;
            }

            /**
             * Sets the value of the suiteName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSuiteName(String value) {
                this.suiteName = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="IPData" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="BumpCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="DateCreated" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
     *                   &lt;element name="IPID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="ProductLineID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="ProductReleaseID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="ProductReleaseName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="SuiteID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="SuiteName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ipData"
    })
    public static class DetailIPData {

        @XmlElement(name = "IPData")
        protected List<EndUserData.DetailIPData.IPData> ipData;

        /**
         * Gets the value of the ipData property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ipData property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIPData().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EndUserData.DetailIPData.IPData }
         * 
         * 
         */
        public List<EndUserData.DetailIPData.IPData> getIPData() {
            if (ipData == null) {
                ipData = new ArrayList<EndUserData.DetailIPData.IPData>();
            }
            return this.ipData;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="BumpCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="DateCreated" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
         *         &lt;element name="IPID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="ProductLineID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="ProductReleaseID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="ProductReleaseName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="SuiteID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="SuiteName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "bumpCount",
            "dateCreated",
            "ipid",
            "productLineID",
            "productReleaseID",
            "productReleaseName",
            "suiteID",
            "suiteName"
        })
        public static class IPData {

            @XmlElement(name = "BumpCount")
            protected Integer bumpCount;
            @XmlElement(name = "DateCreated")
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar dateCreated;
            @XmlElement(name = "IPID")
            protected Integer ipid;
            @XmlElement(name = "ProductLineID")
            protected Integer productLineID;
            @XmlElement(name = "ProductReleaseID")
            protected Integer productReleaseID;
            @XmlElement(name = "ProductReleaseName")
            protected String productReleaseName;
            @XmlElement(name = "SuiteID")
            protected Integer suiteID;
            @XmlElement(name = "SuiteName")
            protected String suiteName;

            /**
             * Gets the value of the bumpCount property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getBumpCount() {
                return bumpCount;
            }

            /**
             * Sets the value of the bumpCount property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBumpCount(Integer value) {
                this.bumpCount = value;
            }

            /**
             * Gets the value of the dateCreated property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDateCreated() {
                return dateCreated;
            }

            /**
             * Sets the value of the dateCreated property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDateCreated(XMLGregorianCalendar value) {
                this.dateCreated = value;
            }

            /**
             * Gets the value of the ipid property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getIPID() {
                return ipid;
            }

            /**
             * Sets the value of the ipid property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setIPID(Integer value) {
                this.ipid = value;
            }

            /**
             * Gets the value of the productLineID property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getProductLineID() {
                return productLineID;
            }

            /**
             * Sets the value of the productLineID property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setProductLineID(Integer value) {
                this.productLineID = value;
            }

            /**
             * Gets the value of the productReleaseID property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getProductReleaseID() {
                return productReleaseID;
            }

            /**
             * Sets the value of the productReleaseID property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setProductReleaseID(Integer value) {
                this.productReleaseID = value;
            }

            /**
             * Gets the value of the productReleaseName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProductReleaseName() {
                return productReleaseName;
            }

            /**
             * Sets the value of the productReleaseName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProductReleaseName(String value) {
                this.productReleaseName = value;
            }

            /**
             * Gets the value of the suiteID property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getSuiteID() {
                return suiteID;
            }

            /**
             * Sets the value of the suiteID property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setSuiteID(Integer value) {
                this.suiteID = value;
            }

            /**
             * Gets the value of the suiteName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSuiteName() {
                return suiteName;
            }

            /**
             * Sets the value of the suiteName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSuiteName(String value) {
                this.suiteName = value;
            }

        }

    }

}
