//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.16 at 09:44:55 AM EDT 
//


package citrite;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="End_User_Org_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="End_User_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="End_User_Geo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="End_User_Area" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="End_User_Territory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="End_User_Region" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="End_User_SubArea" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="End_User_SalesArea" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="End_User_District" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="End_User_State" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="End_User_Country_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="End_User_Country_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="End_User_Email_Address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="High_Touch_Flag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "endUserOrgID",
    "endUserName",
    "endUserGeo",
    "endUserArea",
    "endUserTerritory",
    "endUserRegion",
    "endUserSubArea",
    "endUserSalesArea",
    "endUserDistrict",
    "endUserState",
    "endUserCountryName",
    "endUserCountryCode",
    "endUserEmailAddress",
    "highTouchFlag"
})
public class EndUserInfo {

    @XmlElement(name = "End_User_Org_ID")
    protected String endUserOrgID;
    @XmlElement(name = "End_User_Name")
    protected String endUserName;
    @XmlElement(name = "End_User_Geo")
    protected String endUserGeo;
    @XmlElement(name = "End_User_Area")
    protected String endUserArea;
    @XmlElement(name = "End_User_Territory")
    protected String endUserTerritory;
    @XmlElement(name = "End_User_Region")
    protected String endUserRegion;
    @XmlElement(name = "End_User_SubArea")
    protected String endUserSubArea;
    @XmlElement(name = "End_User_SalesArea")
    protected String endUserSalesArea;
    @XmlElement(name = "End_User_District")
    protected String endUserDistrict;
    @XmlElement(name = "End_User_State")
    protected String endUserState;
    @XmlElement(name = "End_User_Country_Name")
    protected String endUserCountryName;
    @XmlElement(name = "End_User_Country_Code")
    protected String endUserCountryCode;
    @XmlElement(name = "End_User_Email_Address")
    protected String endUserEmailAddress;
    @XmlElementRef(name = "High_Touch_Flag", type = JAXBElement.class, required = false)
    protected JAXBElement<Boolean> highTouchFlag;

    /**
     * Gets the value of the endUserOrgID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndUserOrgID() {
        return endUserOrgID;
    }

    /**
     * Sets the value of the endUserOrgID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndUserOrgID(String value) {
        this.endUserOrgID = value;
    }

    /**
     * Gets the value of the endUserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndUserName() {
        return endUserName;
    }

    /**
     * Sets the value of the endUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndUserName(String value) {
        this.endUserName = value;
    }

    /**
     * Gets the value of the endUserGeo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndUserGeo() {
        return endUserGeo;
    }

    /**
     * Sets the value of the endUserGeo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndUserGeo(String value) {
        this.endUserGeo = value;
    }

    /**
     * Gets the value of the endUserArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndUserArea() {
        return endUserArea;
    }

    /**
     * Sets the value of the endUserArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndUserArea(String value) {
        this.endUserArea = value;
    }

    /**
     * Gets the value of the endUserTerritory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndUserTerritory() {
        return endUserTerritory;
    }

    /**
     * Sets the value of the endUserTerritory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndUserTerritory(String value) {
        this.endUserTerritory = value;
    }

    /**
     * Gets the value of the endUserRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndUserRegion() {
        return endUserRegion;
    }

    /**
     * Sets the value of the endUserRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndUserRegion(String value) {
        this.endUserRegion = value;
    }

    /**
     * Gets the value of the endUserSubArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndUserSubArea() {
        return endUserSubArea;
    }

    /**
     * Sets the value of the endUserSubArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndUserSubArea(String value) {
        this.endUserSubArea = value;
    }

    /**
     * Gets the value of the endUserSalesArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndUserSalesArea() {
        return endUserSalesArea;
    }

    /**
     * Sets the value of the endUserSalesArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndUserSalesArea(String value) {
        this.endUserSalesArea = value;
    }

    /**
     * Gets the value of the endUserDistrict property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndUserDistrict() {
        return endUserDistrict;
    }

    /**
     * Sets the value of the endUserDistrict property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndUserDistrict(String value) {
        this.endUserDistrict = value;
    }

    /**
     * Gets the value of the endUserState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndUserState() {
        return endUserState;
    }

    /**
     * Sets the value of the endUserState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndUserState(String value) {
        this.endUserState = value;
    }

    /**
     * Gets the value of the endUserCountryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndUserCountryName() {
        return endUserCountryName;
    }

    /**
     * Sets the value of the endUserCountryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndUserCountryName(String value) {
        this.endUserCountryName = value;
    }

    /**
     * Gets the value of the endUserCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndUserCountryCode() {
        return endUserCountryCode;
    }

    /**
     * Sets the value of the endUserCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndUserCountryCode(String value) {
        this.endUserCountryCode = value;
    }

    /**
     * Gets the value of the endUserEmailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndUserEmailAddress() {
        return endUserEmailAddress;
    }

    /**
     * Sets the value of the endUserEmailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndUserEmailAddress(String value) {
        this.endUserEmailAddress = value;
    }

    /**
     * Gets the value of the highTouchFlag property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public JAXBElement<Boolean> getHighTouchFlag() {
        return highTouchFlag;
    }

    /**
     * Sets the value of the highTouchFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public void setHighTouchFlag(JAXBElement<Boolean> value) {
        this.highTouchFlag = value;
    }

}
