//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.16 at 09:44:55 AM EDT 
//


package citrite;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the citrite package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EndUserInfo_QNAME = new QName("urn:schemas-citrite-net:pip:sfdc:enduser:1", "EndUserInfo");
    private final static QName _Payout_QNAME = new QName("urn:schemas-citrite-net:pip:bre:payout:1", "Payout");
    private final static QName _Request_QNAME = new QName("urn:schemas-citrite-net:pip:sfdc:val-calc-request:1", "Request");
    private final static QName _Order_QNAME = new QName("urn:schemas-citrite-net:pip:sfdc:order:1", "Order");
    private final static QName _Validations_QNAME = new QName("urn:schemas-citrite-net:pip:bre:validations:1", "Validations");
    private final static QName _OrderOrderHeaderSharedRewardFlag_QNAME = new QName("", "Shared_Reward_Flag");
    private final static QName _EndUserInfoHighTouchFlag_QNAME = new QName("", "High_Touch_Flag");
    private final static QName _OrderOrderLineItemsOrderLineItemPartnerIncentiveEligibleFlag_QNAME = new QName("", "Partner_Incentive_Eligible_Flag");
    private final static QName _OrderOrderLineItemsOrderLineItemFailureReasons_QNAME = new QName("", "Failure_Reasons");
    private final static QName _OrderOrderLineItemsOrderLineItemPartnerEligible_QNAME = new QName("", "Partner_Eligible");
    private final static QName _InfoErrors_QNAME = new QName("", "Errors");
    private final static QName _RewardRegistrationBackendApplicableFlag_QNAME = new QName("", "BackendApplicable_Flag");
    private final static QName _RewardRegistrationFrontendApplicableFlag_QNAME = new QName("", "FrontendApplicable_Flag");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: citrite
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Info }
     * 
     */
    public Info createInfo() {
        return new Info();
    }

    /**
     * Create an instance of {@link EndUserData }
     * 
     */
    public EndUserData createEndUserData() {
        return new EndUserData();
    }

    /**
     * Create an instance of {@link CharacteristicsData }
     * 
     */
    public CharacteristicsData createCharacteristicsData() {
        return new CharacteristicsData();
    }

    /**
     * Create an instance of {@link ProductReleaseData }
     * 
     */
    public ProductReleaseData createProductReleaseData() {
        return new ProductReleaseData();
    }

    /**
     * Create an instance of {@link PartnerInfo }
     * 
     */
    public PartnerInfo createPartnerInfo() {
        return new PartnerInfo();
    }

    /**
     * Create an instance of {@link ProductAuthorizations }
     * 
     */
    public ProductAuthorizations createProductAuthorizations() {
        return new ProductAuthorizations();
    }

    /**
     * Create an instance of {@link SalesExceptions }
     * 
     */
    public SalesExceptions createSalesExceptions() {
        return new SalesExceptions();
    }

    /**
     * Create an instance of {@link Specializations }
     * 
     */
    public Specializations createSpecializations() {
        return new Specializations();
    }

    /**
     * Create an instance of {@link Specializations.Specialization }
     * 
     */
    public Specializations.Specialization createSpecializationsSpecialization() {
        return new Specializations.Specialization();
    }

    /**
     * Create an instance of {@link Order }
     * 
     */
    public Order createOrder() {
        return new Order();
    }

    /**
     * Create an instance of {@link Order.OrderLineItems }
     * 
     */
    public Order.OrderLineItems createOrderOrderLineItems() {
        return new Order.OrderLineItems();
    }

    /**
     * Create an instance of {@link Order.OrderLineItems.OrderLineItem }
     * 
     */
    public Order.OrderLineItems.OrderLineItem createOrderOrderLineItemsOrderLineItem() {
        return new Order.OrderLineItems.OrderLineItem();
    }

    /**
     * Create an instance of {@link Order.OrderLineItems.OrderLineItem.OrderDiscounts }
     * 
     */
    public Order.OrderLineItems.OrderLineItem.OrderDiscounts createOrderOrderLineItemsOrderLineItemOrderDiscounts() {
        return new Order.OrderLineItems.OrderLineItem.OrderDiscounts();
    }

    /**
     * Create an instance of {@link Order.OrderHeader }
     * 
     */
    public Order.OrderHeader createOrderOrderHeader() {
        return new Order.OrderHeader();
    }

    /**
     * Create an instance of {@link Order.OrderHeader.OrderDiscounts }
     * 
     */
    public Order.OrderHeader.OrderDiscounts createOrderOrderHeaderOrderDiscounts() {
        return new Order.OrderHeader.OrderDiscounts();
    }

    /**
     * Create an instance of {@link EndUserData.DetailIPData }
     * 
     */
    public EndUserData.DetailIPData createEndUserDataDetailIPData() {
        return new EndUserData.DetailIPData();
    }

    /**
     * Create an instance of {@link EndUserData.AggregatedIPData }
     * 
     */
    public EndUserData.AggregatedIPData createEndUserDataAggregatedIPData() {
        return new EndUserData.AggregatedIPData();
    }

    /**
     * Create an instance of {@link Info.Errors }
     * 
     */
    public Info.Errors createInfoErrors() {
        return new Info.Errors();
    }

    /**
     * Create an instance of {@link Payout }
     * 
     */
    public Payout createPayout() {
        return new Payout();
    }

    /**
     * Create an instance of {@link Payout.PayoutLineItems }
     * 
     */
    public Payout.PayoutLineItems createPayoutPayoutLineItems() {
        return new Payout.PayoutLineItems();
    }

    /**
     * Create an instance of {@link Payout.PayoutLineItems.PayoutLineItem }
     * 
     */
    public Payout.PayoutLineItems.PayoutLineItem createPayoutPayoutLineItemsPayoutLineItem() {
        return new Payout.PayoutLineItems.PayoutLineItem();
    }

    /**
     * Create an instance of {@link Payout.PayoutLineItems.PayoutLineItem.Promos }
     * 
     */
    public Payout.PayoutLineItems.PayoutLineItem.Promos createPayoutPayoutLineItemsPayoutLineItemPromos() {
        return new Payout.PayoutLineItems.PayoutLineItem.Promos();
    }

    /**
     * Create an instance of {@link Validations }
     * 
     */
    public Validations createValidations() {
        return new Validations();
    }

    /**
     * Create an instance of {@link BREObjectSFDC }
     * 
     */
    public BREObjectSFDC createBREObjectSFDC() {
        return new BREObjectSFDC();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link CharacteristicsData.Characteristic }
     * 
     */
    public CharacteristicsData.Characteristic createCharacteristicsDataCharacteristic() {
        return new CharacteristicsData.Characteristic();
    }

    /**
     * Create an instance of {@link ProductReleaseData.ProductReleaseRecord }
     * 
     */
    public ProductReleaseData.ProductReleaseRecord createProductReleaseDataProductReleaseRecord() {
        return new ProductReleaseData.ProductReleaseRecord();
    }

    /**
     * Create an instance of {@link PartnerInfo.Tags }
     * 
     */
    public PartnerInfo.Tags createPartnerInfoTags() {
        return new PartnerInfo.Tags();
    }

    /**
     * Create an instance of {@link RewardRegistration }
     * 
     */
    public RewardRegistration createRewardRegistration() {
        return new RewardRegistration();
    }

    /**
     * Create an instance of {@link OriginalOrder }
     * 
     */
    public OriginalOrder createOriginalOrder() {
        return new OriginalOrder();
    }

    /**
     * Create an instance of {@link PartnerFunctions }
     * 
     */
    public PartnerFunctions createPartnerFunctions() {
        return new PartnerFunctions();
    }

    /**
     * Create an instance of {@link ProductAuthorizations.AuthorizationItem }
     * 
     */
    public ProductAuthorizations.AuthorizationItem createProductAuthorizationsAuthorizationItem() {
        return new ProductAuthorizations.AuthorizationItem();
    }

    /**
     * Create an instance of {@link SalesExceptions.SalesException }
     * 
     */
    public SalesExceptions.SalesException createSalesExceptionsSalesException() {
        return new SalesExceptions.SalesException();
    }

    /**
     * Create an instance of {@link EndUserInfo }
     * 
     */
    public EndUserInfo createEndUserInfo() {
        return new EndUserInfo();
    }

    /**
     * Create an instance of {@link Specializations.Specialization.AddData }
     * 
     */
    public Specializations.Specialization.AddData createSpecializationsSpecializationAddData() {
        return new Specializations.Specialization.AddData();
    }

    /**
     * Create an instance of {@link Order.OrderLineItems.OrderLineItem.OrderDiscounts.OrderDiscount }
     * 
     */
    public Order.OrderLineItems.OrderLineItem.OrderDiscounts.OrderDiscount createOrderOrderLineItemsOrderLineItemOrderDiscountsOrderDiscount() {
        return new Order.OrderLineItems.OrderLineItem.OrderDiscounts.OrderDiscount();
    }

    /**
     * Create an instance of {@link Order.OrderHeader.OrderDiscounts.OrderDiscount }
     * 
     */
    public Order.OrderHeader.OrderDiscounts.OrderDiscount createOrderOrderHeaderOrderDiscountsOrderDiscount() {
        return new Order.OrderHeader.OrderDiscounts.OrderDiscount();
    }

    /**
     * Create an instance of {@link EndUserData.DetailIPData.IPData }
     * 
     */
    public EndUserData.DetailIPData.IPData createEndUserDataDetailIPDataIPData() {
        return new EndUserData.DetailIPData.IPData();
    }

    /**
     * Create an instance of {@link EndUserData.AggregatedIPData.IPData }
     * 
     */
    public EndUserData.AggregatedIPData.IPData createEndUserDataAggregatedIPDataIPData() {
        return new EndUserData.AggregatedIPData.IPData();
    }

    /**
     * Create an instance of {@link Info.Errors.Error }
     * 
     */
    public Info.Errors.Error createInfoErrorsError() {
        return new Info.Errors.Error();
    }

    /**
     * Create an instance of {@link Payout.PayoutHeader }
     * 
     */
    public Payout.PayoutHeader createPayoutPayoutHeader() {
        return new Payout.PayoutHeader();
    }

    /**
     * Create an instance of {@link Payout.PayoutLineItems.PayoutLineItem.Promos.Promo }
     * 
     */
    public Payout.PayoutLineItems.PayoutLineItem.Promos.Promo createPayoutPayoutLineItemsPayoutLineItemPromosPromo() {
        return new Payout.PayoutLineItems.PayoutLineItem.Promos.Promo();
    }

    /**
     * Create an instance of {@link Validations.Validation }
     * 
     */
    public Validations.Validation createValidationsValidation() {
        return new Validations.Validation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndUserInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-citrite-net:pip:sfdc:enduser:1", name = "EndUserInfo")
    public JAXBElement<EndUserInfo> createEndUserInfo(EndUserInfo value) {
        return new JAXBElement<EndUserInfo>(_EndUserInfo_QNAME, EndUserInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Payout }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-citrite-net:pip:bre:payout:1", name = "Payout")
    public JAXBElement<Payout> createPayout(Payout value) {
        return new JAXBElement<Payout>(_Payout_QNAME, Payout.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Request }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-citrite-net:pip:sfdc:val-calc-request:1", name = "Request")
    public JAXBElement<Request> createRequest(Request value) {
        return new JAXBElement<Request>(_Request_QNAME, Request.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Order }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-citrite-net:pip:sfdc:order:1", name = "Order")
    public JAXBElement<Order> createOrder(Order value) {
        return new JAXBElement<Order>(_Order_QNAME, Order.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Validations }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-citrite-net:pip:bre:validations:1", name = "Validations")
    public JAXBElement<Validations> createValidations(Validations value) {
        return new JAXBElement<Validations>(_Validations_QNAME, Validations.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Shared_Reward_Flag", scope = Order.OrderHeader.class)
    public JAXBElement<Boolean> createOrderOrderHeaderSharedRewardFlag(Boolean value) {
        return new JAXBElement<Boolean>(_OrderOrderHeaderSharedRewardFlag_QNAME, Boolean.class, Order.OrderHeader.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "High_Touch_Flag", scope = EndUserInfo.class)
    public JAXBElement<Boolean> createEndUserInfoHighTouchFlag(Boolean value) {
        return new JAXBElement<Boolean>(_EndUserInfoHighTouchFlag_QNAME, Boolean.class, EndUserInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Partner_Incentive_Eligible_Flag", scope = Order.OrderLineItems.OrderLineItem.class)
    public JAXBElement<Boolean> createOrderOrderLineItemsOrderLineItemPartnerIncentiveEligibleFlag(Boolean value) {
        return new JAXBElement<Boolean>(_OrderOrderLineItemsOrderLineItemPartnerIncentiveEligibleFlag_QNAME, Boolean.class, Order.OrderLineItems.OrderLineItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Failure_Reasons", scope = Order.OrderLineItems.OrderLineItem.class)
    public JAXBElement<String> createOrderOrderLineItemsOrderLineItemFailureReasons(String value) {
        return new JAXBElement<String>(_OrderOrderLineItemsOrderLineItemFailureReasons_QNAME, String.class, Order.OrderLineItems.OrderLineItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Partner_Eligible", scope = Order.OrderLineItems.OrderLineItem.class)
    public JAXBElement<Boolean> createOrderOrderLineItemsOrderLineItemPartnerEligible(Boolean value) {
        return new JAXBElement<Boolean>(_OrderOrderLineItemsOrderLineItemPartnerEligible_QNAME, Boolean.class, Order.OrderLineItems.OrderLineItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Info.Errors }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Errors", scope = Info.class)
    public JAXBElement<Info.Errors> createInfoErrors(Info.Errors value) {
        return new JAXBElement<Info.Errors>(_InfoErrors_QNAME, Info.Errors.class, Info.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BackendApplicable_Flag", scope = RewardRegistration.class)
    public JAXBElement<Boolean> createRewardRegistrationBackendApplicableFlag(Boolean value) {
        return new JAXBElement<Boolean>(_RewardRegistrationBackendApplicableFlag_QNAME, Boolean.class, RewardRegistration.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FrontendApplicable_Flag", scope = RewardRegistration.class)
    public JAXBElement<Boolean> createRewardRegistrationFrontendApplicableFlag(Boolean value) {
        return new JAXBElement<Boolean>(_RewardRegistrationFrontendApplicableFlag_QNAME, Boolean.class, RewardRegistration.class, value);
    }

}
