//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.16 at 09:44:55 AM EDT 
//


package citrite;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="BillTo_Org_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BillTo_Partner_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BillTo_Address_Line1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BillTo_Address_Line2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BillTo_City" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BillTo_State" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BillTo_Country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BillTo_Postal_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BillTo_District" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BillTo_Email_Address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BillTo_User_Country_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SoldTo_Org_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SoldTo_Partner_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SoldTo_Address_Line1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SoldTo_Address_Line2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SoldTo_City" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SoldTo_State" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SoldTo_Country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SoldTo_Postal_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SoldTo_District" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SoldTo_Email_Address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SoldTo_User_Country_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShipTo_Org_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShipTo_Partner_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShipTo_Address_Line1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShipTo_Address_Line2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShipTo_City" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShipTo_State" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShipTo_Country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShipTo_Postal_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShipTo_District" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShipTo_Email_Address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShipTo_User_Country_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Reseller_Org_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Reseller_Partner_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Reseller_Address_Line1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Reseller_Address_Line2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Reseller_City" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Reseller_State" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Reseller_Country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Reseller_Postal_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Reseller_District" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Reseller_Email_Address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Reseller_User_Country_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "billToOrgID",
    "billToPartnerName",
    "billToAddressLine1",
    "billToAddressLine2",
    "billToCity",
    "billToState",
    "billToCountry",
    "billToPostalCode",
    "billToDistrict",
    "billToEmailAddress",
    "billToUserCountryCode",
    "soldToOrgID",
    "soldToPartnerName",
    "soldToAddressLine1",
    "soldToAddressLine2",
    "soldToCity",
    "soldToState",
    "soldToCountry",
    "soldToPostalCode",
    "soldToDistrict",
    "soldToEmailAddress",
    "soldToUserCountryCode",
    "shipToOrgID",
    "shipToPartnerName",
    "shipToAddressLine1",
    "shipToAddressLine2",
    "shipToCity",
    "shipToState",
    "shipToCountry",
    "shipToPostalCode",
    "shipToDistrict",
    "shipToEmailAddress",
    "shipToUserCountryCode",
    "resellerOrgID",
    "resellerPartnerName",
    "resellerAddressLine1",
    "resellerAddressLine2",
    "resellerCity",
    "resellerState",
    "resellerCountry",
    "resellerPostalCode",
    "resellerDistrict",
    "resellerEmailAddress",
    "resellerUserCountryCode"
})
@XmlRootElement(name = "PartnerFunctions", namespace = "urn:schemas-citrite-net:pip:sfdc:partnerfunctions:1")
public class PartnerFunctions {

    @XmlElement(name = "BillTo_Org_ID")
    protected String billToOrgID;
    @XmlElement(name = "BillTo_Partner_Name")
    protected String billToPartnerName;
    @XmlElement(name = "BillTo_Address_Line1")
    protected String billToAddressLine1;
    @XmlElement(name = "BillTo_Address_Line2")
    protected String billToAddressLine2;
    @XmlElement(name = "BillTo_City")
    protected String billToCity;
    @XmlElement(name = "BillTo_State")
    protected String billToState;
    @XmlElement(name = "BillTo_Country")
    protected String billToCountry;
    @XmlElement(name = "BillTo_Postal_Code")
    protected String billToPostalCode;
    @XmlElement(name = "BillTo_District")
    protected String billToDistrict;
    @XmlElement(name = "BillTo_Email_Address")
    protected String billToEmailAddress;
    @XmlElement(name = "BillTo_User_Country_Code")
    protected String billToUserCountryCode;
    @XmlElement(name = "SoldTo_Org_ID")
    protected String soldToOrgID;
    @XmlElement(name = "SoldTo_Partner_Name")
    protected String soldToPartnerName;
    @XmlElement(name = "SoldTo_Address_Line1")
    protected String soldToAddressLine1;
    @XmlElement(name = "SoldTo_Address_Line2")
    protected String soldToAddressLine2;
    @XmlElement(name = "SoldTo_City")
    protected String soldToCity;
    @XmlElement(name = "SoldTo_State")
    protected String soldToState;
    @XmlElement(name = "SoldTo_Country")
    protected String soldToCountry;
    @XmlElement(name = "SoldTo_Postal_Code")
    protected String soldToPostalCode;
    @XmlElement(name = "SoldTo_District")
    protected String soldToDistrict;
    @XmlElement(name = "SoldTo_Email_Address")
    protected String soldToEmailAddress;
    @XmlElement(name = "SoldTo_User_Country_Code")
    protected String soldToUserCountryCode;
    @XmlElement(name = "ShipTo_Org_ID")
    protected String shipToOrgID;
    @XmlElement(name = "ShipTo_Partner_Name")
    protected String shipToPartnerName;
    @XmlElement(name = "ShipTo_Address_Line1")
    protected String shipToAddressLine1;
    @XmlElement(name = "ShipTo_Address_Line2")
    protected String shipToAddressLine2;
    @XmlElement(name = "ShipTo_City")
    protected String shipToCity;
    @XmlElement(name = "ShipTo_State")
    protected String shipToState;
    @XmlElement(name = "ShipTo_Country")
    protected String shipToCountry;
    @XmlElement(name = "ShipTo_Postal_Code")
    protected String shipToPostalCode;
    @XmlElement(name = "ShipTo_District")
    protected String shipToDistrict;
    @XmlElement(name = "ShipTo_Email_Address")
    protected String shipToEmailAddress;
    @XmlElement(name = "ShipTo_User_Country_Code")
    protected String shipToUserCountryCode;
    @XmlElement(name = "Reseller_Org_ID")
    protected String resellerOrgID;
    @XmlElement(name = "Reseller_Partner_Name")
    protected String resellerPartnerName;
    @XmlElement(name = "Reseller_Address_Line1")
    protected String resellerAddressLine1;
    @XmlElement(name = "Reseller_Address_Line2")
    protected String resellerAddressLine2;
    @XmlElement(name = "Reseller_City")
    protected String resellerCity;
    @XmlElement(name = "Reseller_State")
    protected String resellerState;
    @XmlElement(name = "Reseller_Country")
    protected String resellerCountry;
    @XmlElement(name = "Reseller_Postal_Code")
    protected String resellerPostalCode;
    @XmlElement(name = "Reseller_District")
    protected String resellerDistrict;
    @XmlElement(name = "Reseller_Email_Address")
    protected String resellerEmailAddress;
    @XmlElement(name = "Reseller_User_Country_Code")
    protected String resellerUserCountryCode;

    /**
     * Gets the value of the billToOrgID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToOrgID() {
        return billToOrgID;
    }

    /**
     * Sets the value of the billToOrgID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToOrgID(String value) {
        this.billToOrgID = value;
    }

    /**
     * Gets the value of the billToPartnerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToPartnerName() {
        return billToPartnerName;
    }

    /**
     * Sets the value of the billToPartnerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToPartnerName(String value) {
        this.billToPartnerName = value;
    }

    /**
     * Gets the value of the billToAddressLine1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToAddressLine1() {
        return billToAddressLine1;
    }

    /**
     * Sets the value of the billToAddressLine1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToAddressLine1(String value) {
        this.billToAddressLine1 = value;
    }

    /**
     * Gets the value of the billToAddressLine2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToAddressLine2() {
        return billToAddressLine2;
    }

    /**
     * Sets the value of the billToAddressLine2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToAddressLine2(String value) {
        this.billToAddressLine2 = value;
    }

    /**
     * Gets the value of the billToCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToCity() {
        return billToCity;
    }

    /**
     * Sets the value of the billToCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToCity(String value) {
        this.billToCity = value;
    }

    /**
     * Gets the value of the billToState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToState() {
        return billToState;
    }

    /**
     * Sets the value of the billToState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToState(String value) {
        this.billToState = value;
    }

    /**
     * Gets the value of the billToCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToCountry() {
        return billToCountry;
    }

    /**
     * Sets the value of the billToCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToCountry(String value) {
        this.billToCountry = value;
    }

    /**
     * Gets the value of the billToPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToPostalCode() {
        return billToPostalCode;
    }

    /**
     * Sets the value of the billToPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToPostalCode(String value) {
        this.billToPostalCode = value;
    }

    /**
     * Gets the value of the billToDistrict property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToDistrict() {
        return billToDistrict;
    }

    /**
     * Sets the value of the billToDistrict property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToDistrict(String value) {
        this.billToDistrict = value;
    }

    /**
     * Gets the value of the billToEmailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToEmailAddress() {
        return billToEmailAddress;
    }

    /**
     * Sets the value of the billToEmailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToEmailAddress(String value) {
        this.billToEmailAddress = value;
    }

    /**
     * Gets the value of the billToUserCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToUserCountryCode() {
        return billToUserCountryCode;
    }

    /**
     * Sets the value of the billToUserCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToUserCountryCode(String value) {
        this.billToUserCountryCode = value;
    }

    /**
     * Gets the value of the soldToOrgID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoldToOrgID() {
        return soldToOrgID;
    }

    /**
     * Sets the value of the soldToOrgID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoldToOrgID(String value) {
        this.soldToOrgID = value;
    }

    /**
     * Gets the value of the soldToPartnerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoldToPartnerName() {
        return soldToPartnerName;
    }

    /**
     * Sets the value of the soldToPartnerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoldToPartnerName(String value) {
        this.soldToPartnerName = value;
    }

    /**
     * Gets the value of the soldToAddressLine1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoldToAddressLine1() {
        return soldToAddressLine1;
    }

    /**
     * Sets the value of the soldToAddressLine1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoldToAddressLine1(String value) {
        this.soldToAddressLine1 = value;
    }

    /**
     * Gets the value of the soldToAddressLine2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoldToAddressLine2() {
        return soldToAddressLine2;
    }

    /**
     * Sets the value of the soldToAddressLine2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoldToAddressLine2(String value) {
        this.soldToAddressLine2 = value;
    }

    /**
     * Gets the value of the soldToCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoldToCity() {
        return soldToCity;
    }

    /**
     * Sets the value of the soldToCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoldToCity(String value) {
        this.soldToCity = value;
    }

    /**
     * Gets the value of the soldToState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoldToState() {
        return soldToState;
    }

    /**
     * Sets the value of the soldToState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoldToState(String value) {
        this.soldToState = value;
    }

    /**
     * Gets the value of the soldToCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoldToCountry() {
        return soldToCountry;
    }

    /**
     * Sets the value of the soldToCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoldToCountry(String value) {
        this.soldToCountry = value;
    }

    /**
     * Gets the value of the soldToPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoldToPostalCode() {
        return soldToPostalCode;
    }

    /**
     * Sets the value of the soldToPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoldToPostalCode(String value) {
        this.soldToPostalCode = value;
    }

    /**
     * Gets the value of the soldToDistrict property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoldToDistrict() {
        return soldToDistrict;
    }

    /**
     * Sets the value of the soldToDistrict property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoldToDistrict(String value) {
        this.soldToDistrict = value;
    }

    /**
     * Gets the value of the soldToEmailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoldToEmailAddress() {
        return soldToEmailAddress;
    }

    /**
     * Sets the value of the soldToEmailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoldToEmailAddress(String value) {
        this.soldToEmailAddress = value;
    }

    /**
     * Gets the value of the soldToUserCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoldToUserCountryCode() {
        return soldToUserCountryCode;
    }

    /**
     * Sets the value of the soldToUserCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoldToUserCountryCode(String value) {
        this.soldToUserCountryCode = value;
    }

    /**
     * Gets the value of the shipToOrgID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipToOrgID() {
        return shipToOrgID;
    }

    /**
     * Sets the value of the shipToOrgID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipToOrgID(String value) {
        this.shipToOrgID = value;
    }

    /**
     * Gets the value of the shipToPartnerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipToPartnerName() {
        return shipToPartnerName;
    }

    /**
     * Sets the value of the shipToPartnerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipToPartnerName(String value) {
        this.shipToPartnerName = value;
    }

    /**
     * Gets the value of the shipToAddressLine1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipToAddressLine1() {
        return shipToAddressLine1;
    }

    /**
     * Sets the value of the shipToAddressLine1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipToAddressLine1(String value) {
        this.shipToAddressLine1 = value;
    }

    /**
     * Gets the value of the shipToAddressLine2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipToAddressLine2() {
        return shipToAddressLine2;
    }

    /**
     * Sets the value of the shipToAddressLine2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipToAddressLine2(String value) {
        this.shipToAddressLine2 = value;
    }

    /**
     * Gets the value of the shipToCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipToCity() {
        return shipToCity;
    }

    /**
     * Sets the value of the shipToCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipToCity(String value) {
        this.shipToCity = value;
    }

    /**
     * Gets the value of the shipToState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipToState() {
        return shipToState;
    }

    /**
     * Sets the value of the shipToState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipToState(String value) {
        this.shipToState = value;
    }

    /**
     * Gets the value of the shipToCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipToCountry() {
        return shipToCountry;
    }

    /**
     * Sets the value of the shipToCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipToCountry(String value) {
        this.shipToCountry = value;
    }

    /**
     * Gets the value of the shipToPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipToPostalCode() {
        return shipToPostalCode;
    }

    /**
     * Sets the value of the shipToPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipToPostalCode(String value) {
        this.shipToPostalCode = value;
    }

    /**
     * Gets the value of the shipToDistrict property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipToDistrict() {
        return shipToDistrict;
    }

    /**
     * Sets the value of the shipToDistrict property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipToDistrict(String value) {
        this.shipToDistrict = value;
    }

    /**
     * Gets the value of the shipToEmailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipToEmailAddress() {
        return shipToEmailAddress;
    }

    /**
     * Sets the value of the shipToEmailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipToEmailAddress(String value) {
        this.shipToEmailAddress = value;
    }

    /**
     * Gets the value of the shipToUserCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipToUserCountryCode() {
        return shipToUserCountryCode;
    }

    /**
     * Sets the value of the shipToUserCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipToUserCountryCode(String value) {
        this.shipToUserCountryCode = value;
    }

    /**
     * Gets the value of the resellerOrgID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResellerOrgID() {
        return resellerOrgID;
    }

    /**
     * Sets the value of the resellerOrgID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResellerOrgID(String value) {
        this.resellerOrgID = value;
    }

    /**
     * Gets the value of the resellerPartnerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResellerPartnerName() {
        return resellerPartnerName;
    }

    /**
     * Sets the value of the resellerPartnerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResellerPartnerName(String value) {
        this.resellerPartnerName = value;
    }

    /**
     * Gets the value of the resellerAddressLine1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResellerAddressLine1() {
        return resellerAddressLine1;
    }

    /**
     * Sets the value of the resellerAddressLine1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResellerAddressLine1(String value) {
        this.resellerAddressLine1 = value;
    }

    /**
     * Gets the value of the resellerAddressLine2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResellerAddressLine2() {
        return resellerAddressLine2;
    }

    /**
     * Sets the value of the resellerAddressLine2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResellerAddressLine2(String value) {
        this.resellerAddressLine2 = value;
    }

    /**
     * Gets the value of the resellerCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResellerCity() {
        return resellerCity;
    }

    /**
     * Sets the value of the resellerCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResellerCity(String value) {
        this.resellerCity = value;
    }

    /**
     * Gets the value of the resellerState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResellerState() {
        return resellerState;
    }

    /**
     * Sets the value of the resellerState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResellerState(String value) {
        this.resellerState = value;
    }

    /**
     * Gets the value of the resellerCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResellerCountry() {
        return resellerCountry;
    }

    /**
     * Sets the value of the resellerCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResellerCountry(String value) {
        this.resellerCountry = value;
    }

    /**
     * Gets the value of the resellerPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResellerPostalCode() {
        return resellerPostalCode;
    }

    /**
     * Sets the value of the resellerPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResellerPostalCode(String value) {
        this.resellerPostalCode = value;
    }

    /**
     * Gets the value of the resellerDistrict property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResellerDistrict() {
        return resellerDistrict;
    }

    /**
     * Sets the value of the resellerDistrict property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResellerDistrict(String value) {
        this.resellerDistrict = value;
    }

    /**
     * Gets the value of the resellerEmailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResellerEmailAddress() {
        return resellerEmailAddress;
    }

    /**
     * Sets the value of the resellerEmailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResellerEmailAddress(String value) {
        this.resellerEmailAddress = value;
    }

    /**
     * Gets the value of the resellerUserCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResellerUserCountryCode() {
        return resellerUserCountryCode;
    }

    /**
     * Sets the value of the resellerUserCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResellerUserCountryCode(String value) {
        this.resellerUserCountryCode = value;
    }

}
