//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.16 at 09:44:55 AM EDT 
//


package citrite;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="Tags" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TagID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TagName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Partner_Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Partner_Level" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Partner_Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Partner_Geo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Partner_Area" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Partner_SubArea" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Partner_SalesArea" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Partner_Region" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Partner_Territory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Partner_Compliance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Partner_Mship_Start_Date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Partner_Mship_End_Date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Partner_Mship_Inception_Date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tags",
    "partnerType",
    "partnerLevel",
    "partnerStatus",
    "partnerGeo",
    "partnerArea",
    "partnerSubArea",
    "partnerSalesArea",
    "partnerRegion",
    "partnerTerritory",
    "partnerCompliance",
    "partnerMshipStartDate",
    "partnerMshipEndDate",
    "partnerMshipInceptionDate"
})
@XmlRootElement(name = "PartnerInfo", namespace = "urn:schemas-citrite-net:pip:sfdc:partnerInfo:1")
public class PartnerInfo {

    @XmlElement(name = "Tags")
    protected List<PartnerInfo.Tags> tags;
    @XmlElement(name = "Partner_Type")
    protected String partnerType;
    @XmlElement(name = "Partner_Level")
    protected String partnerLevel;
    @XmlElement(name = "Partner_Status")
    protected String partnerStatus;
    @XmlElement(name = "Partner_Geo")
    protected String partnerGeo;
    @XmlElement(name = "Partner_Area")
    protected String partnerArea;
    @XmlElement(name = "Partner_SubArea")
    protected String partnerSubArea;
    @XmlElement(name = "Partner_SalesArea")
    protected String partnerSalesArea;
    @XmlElement(name = "Partner_Region")
    protected String partnerRegion;
    @XmlElement(name = "Partner_Territory")
    protected String partnerTerritory;
    @XmlElement(name = "Partner_Compliance")
    protected String partnerCompliance;
    @XmlElement(name = "Partner_Mship_Start_Date")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar partnerMshipStartDate;
    @XmlElement(name = "Partner_Mship_End_Date")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar partnerMshipEndDate;
    @XmlElement(name = "Partner_Mship_Inception_Date")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar partnerMshipInceptionDate;

    /**
     * Gets the value of the tags property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tags property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTags().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartnerInfo.Tags }
     * 
     * 
     */
    public List<PartnerInfo.Tags> getTags() {
        if (tags == null) {
            tags = new ArrayList<PartnerInfo.Tags>();
        }
        return this.tags;
    }

    /**
     * Gets the value of the partnerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerType() {
        return partnerType;
    }

    /**
     * Sets the value of the partnerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerType(String value) {
        this.partnerType = value;
    }

    /**
     * Gets the value of the partnerLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerLevel() {
        return partnerLevel;
    }

    /**
     * Sets the value of the partnerLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerLevel(String value) {
        this.partnerLevel = value;
    }

    /**
     * Gets the value of the partnerStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerStatus() {
        return partnerStatus;
    }

    /**
     * Sets the value of the partnerStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerStatus(String value) {
        this.partnerStatus = value;
    }

    /**
     * Gets the value of the partnerGeo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerGeo() {
        return partnerGeo;
    }

    /**
     * Sets the value of the partnerGeo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerGeo(String value) {
        this.partnerGeo = value;
    }

    /**
     * Gets the value of the partnerArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerArea() {
        return partnerArea;
    }

    /**
     * Sets the value of the partnerArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerArea(String value) {
        this.partnerArea = value;
    }

    /**
     * Gets the value of the partnerSubArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerSubArea() {
        return partnerSubArea;
    }

    /**
     * Sets the value of the partnerSubArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerSubArea(String value) {
        this.partnerSubArea = value;
    }

    /**
     * Gets the value of the partnerSalesArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerSalesArea() {
        return partnerSalesArea;
    }

    /**
     * Sets the value of the partnerSalesArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerSalesArea(String value) {
        this.partnerSalesArea = value;
    }

    /**
     * Gets the value of the partnerRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerRegion() {
        return partnerRegion;
    }

    /**
     * Sets the value of the partnerRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerRegion(String value) {
        this.partnerRegion = value;
    }

    /**
     * Gets the value of the partnerTerritory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerTerritory() {
        return partnerTerritory;
    }

    /**
     * Sets the value of the partnerTerritory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerTerritory(String value) {
        this.partnerTerritory = value;
    }

    /**
     * Gets the value of the partnerCompliance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerCompliance() {
        return partnerCompliance;
    }

    /**
     * Sets the value of the partnerCompliance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerCompliance(String value) {
        this.partnerCompliance = value;
    }

    /**
     * Gets the value of the partnerMshipStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPartnerMshipStartDate() {
        return partnerMshipStartDate;
    }

    /**
     * Sets the value of the partnerMshipStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPartnerMshipStartDate(XMLGregorianCalendar value) {
        this.partnerMshipStartDate = value;
    }

    /**
     * Gets the value of the partnerMshipEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPartnerMshipEndDate() {
        return partnerMshipEndDate;
    }

    /**
     * Sets the value of the partnerMshipEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPartnerMshipEndDate(XMLGregorianCalendar value) {
        this.partnerMshipEndDate = value;
    }

    /**
     * Gets the value of the partnerMshipInceptionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPartnerMshipInceptionDate() {
        return partnerMshipInceptionDate;
    }

    /**
     * Sets the value of the partnerMshipInceptionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPartnerMshipInceptionDate(XMLGregorianCalendar value) {
        this.partnerMshipInceptionDate = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TagID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TagName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tagID",
        "tagName"
    })
    public static class Tags {

        @XmlElement(name = "TagID", required = true)
        protected String tagID;
        @XmlElement(name = "TagName", required = true)
        protected String tagName;

        /**
         * Gets the value of the tagID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTagID() {
            return tagID;
        }

        /**
         * Sets the value of the tagID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTagID(String value) {
            this.tagID = value;
        }

        /**
         * Gets the value of the tagName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTagName() {
            return tagName;
        }

        /**
         * Sets the value of the tagName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTagName(String value) {
            this.tagName = value;
        }

    }

}
