//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.16 at 09:44:55 AM EDT 
//


package citrite;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="PayoutHeader">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Order_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Payout_Total" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="Payout_Total_Base" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="Payout_Total_Promo" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="Payout_Date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PayoutLineItems">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PayoutLineItem" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="OrderLine_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="SKU_Marketing" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Product_Line_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Edition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="SRP_USD" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                             &lt;element name="Discount_Upfront" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="Discount_Program" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="Discount_Channel" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="Discount_Exception" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="Surcharge_Customer" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="Discount_Upfront_Amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="Discount_Program_Amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="Discount_Channel_Amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="Discount_Exception_Amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="Surcharge_Customer_Amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="Partner_Incentive_Eligible_Flag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="Partner_Eligible" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="Partner_Eligible_Amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="Promo_Total" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="Payout_Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Base_Incentive_Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Base_Percentage" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="Base_ApplyTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Base_Amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="Promos">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Promo" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Number" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Percentage" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                                                 &lt;element name="ApplyTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="AAG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Extension" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Partner_Incentive_Group" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="TransitionPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Purchase_Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="RTM_Material" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="StrategicProgramsPromos" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Quote_Line_Item_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Billing_Frequency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Annual_Contract_Value" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="Total_Contract_Value" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="PolicyName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PolicyVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "payoutHeader",
    "payoutLineItems"
})
public class Payout {

    @XmlElement(name = "PayoutHeader")
    protected Payout.PayoutHeader payoutHeader;
    @XmlElement(name = "PayoutLineItems")
    protected Payout.PayoutLineItems payoutLineItems;
    @XmlAttribute(name = "PolicyName")
    protected String policyName;
    @XmlAttribute(name = "PolicyVersion")
    protected String policyVersion;

    /**
     * Gets the value of the payoutHeader property.
     * 
     * @return
     *     possible object is
     *     {@link Payout.PayoutHeader }
     *     
     */
    public Payout.PayoutHeader getPayoutHeader() {
        return payoutHeader;
    }

    /**
     * Sets the value of the payoutHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link Payout.PayoutHeader }
     *     
     */
    public void setPayoutHeader(Payout.PayoutHeader value) {
        this.payoutHeader = value;
    }

    /**
     * Gets the value of the payoutLineItems property.
     * 
     * @return
     *     possible object is
     *     {@link Payout.PayoutLineItems }
     *     
     */
    public Payout.PayoutLineItems getPayoutLineItems() {
        return payoutLineItems;
    }

    /**
     * Sets the value of the payoutLineItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link Payout.PayoutLineItems }
     *     
     */
    public void setPayoutLineItems(Payout.PayoutLineItems value) {
        this.payoutLineItems = value;
    }

    /**
     * Gets the value of the policyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyName() {
        return policyName;
    }

    /**
     * Sets the value of the policyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyName(String value) {
        this.policyName = value;
    }

    /**
     * Gets the value of the policyVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyVersion() {
        return policyVersion;
    }

    /**
     * Sets the value of the policyVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyVersion(String value) {
        this.policyVersion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Order_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Payout_Total" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="Payout_Total_Base" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="Payout_Total_Promo" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="Payout_Date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "orderID",
        "payoutTotal",
        "payoutTotalBase",
        "payoutTotalPromo",
        "payoutDate"
    })
    public static class PayoutHeader {

        @XmlElement(name = "Order_ID", required = true)
        protected String orderID;
        @XmlElement(name = "Payout_Total", required = true)
        protected BigDecimal payoutTotal;
        @XmlElement(name = "Payout_Total_Base", required = true)
        protected BigDecimal payoutTotalBase;
        @XmlElement(name = "Payout_Total_Promo", required = true)
        protected BigDecimal payoutTotalPromo;
        @XmlElement(name = "Payout_Date", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar payoutDate;

        /**
         * Gets the value of the orderID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderID() {
            return orderID;
        }

        /**
         * Sets the value of the orderID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderID(String value) {
            this.orderID = value;
        }

        /**
         * Gets the value of the payoutTotal property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPayoutTotal() {
            return payoutTotal;
        }

        /**
         * Sets the value of the payoutTotal property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPayoutTotal(BigDecimal value) {
            this.payoutTotal = value;
        }

        /**
         * Gets the value of the payoutTotalBase property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPayoutTotalBase() {
            return payoutTotalBase;
        }

        /**
         * Sets the value of the payoutTotalBase property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPayoutTotalBase(BigDecimal value) {
            this.payoutTotalBase = value;
        }

        /**
         * Gets the value of the payoutTotalPromo property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPayoutTotalPromo() {
            return payoutTotalPromo;
        }

        /**
         * Sets the value of the payoutTotalPromo property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPayoutTotalPromo(BigDecimal value) {
            this.payoutTotalPromo = value;
        }

        /**
         * Gets the value of the payoutDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getPayoutDate() {
            return payoutDate;
        }

        /**
         * Sets the value of the payoutDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setPayoutDate(XMLGregorianCalendar value) {
            this.payoutDate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PayoutLineItem" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="OrderLine_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="SKU_Marketing" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Product_Line_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Edition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="SRP_USD" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="Discount_Upfront" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="Discount_Program" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="Discount_Channel" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="Discount_Exception" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="Surcharge_Customer" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="Discount_Upfront_Amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="Discount_Program_Amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="Discount_Channel_Amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="Discount_Exception_Amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="Surcharge_Customer_Amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="Partner_Incentive_Eligible_Flag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                   &lt;element name="Partner_Eligible" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                   &lt;element name="Partner_Eligible_Amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="Promo_Total" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="Payout_Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Base_Incentive_Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Base_Percentage" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="Base_ApplyTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Base_Amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="Promos">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Promo" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Number" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                       &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="Percentage" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                                       &lt;element name="ApplyTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="AAG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Extension" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Partner_Incentive_Group" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="TransitionPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Purchase_Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="RTM_Material" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="StrategicProgramsPromos" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Quote_Line_Item_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Billing_Frequency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Annual_Contract_Value" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="Total_Contract_Value" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "payoutLineItem"
    })
    public static class PayoutLineItems {

        @XmlElement(name = "PayoutLineItem")
        protected List<Payout.PayoutLineItems.PayoutLineItem> payoutLineItem;

        /**
         * Gets the value of the payoutLineItem property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the payoutLineItem property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPayoutLineItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Payout.PayoutLineItems.PayoutLineItem }
         * 
         * 
         */
        public List<Payout.PayoutLineItems.PayoutLineItem> getPayoutLineItem() {
            if (payoutLineItem == null) {
                payoutLineItem = new ArrayList<Payout.PayoutLineItems.PayoutLineItem>();
            }
            return this.payoutLineItem;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="OrderLine_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="SKU_Marketing" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Product_Line_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Edition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="SRP_USD" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="Discount_Upfront" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="Discount_Program" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="Discount_Channel" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="Discount_Exception" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="Surcharge_Customer" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="Discount_Upfront_Amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="Discount_Program_Amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="Discount_Channel_Amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="Discount_Exception_Amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="Surcharge_Customer_Amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="Partner_Incentive_Eligible_Flag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *         &lt;element name="Partner_Eligible" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *         &lt;element name="Partner_Eligible_Amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="Promo_Total" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="Payout_Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Base_Incentive_Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Base_Percentage" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="Base_ApplyTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Base_Amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="Promos">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Promo" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Number" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                             &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="Percentage" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *                             &lt;element name="ApplyTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="AAG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Extension" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Partner_Incentive_Group" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="TransitionPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Purchase_Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="RTM_Material" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="StrategicProgramsPromos" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Quote_Line_Item_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Billing_Frequency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Annual_Contract_Value" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="Total_Contract_Value" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "orderLineID",
            "skuMarketing",
            "productLineID",
            "edition",
            "srpusd",
            "quantity",
            "discountUpfront",
            "discountProgram",
            "discountChannel",
            "discountException",
            "surchargeCustomer",
            "discountUpfrontAmount",
            "discountProgramAmount",
            "discountChannelAmount",
            "discountExceptionAmount",
            "surchargeCustomerAmount",
            "partnerIncentiveEligibleFlag",
            "partnerEligible",
            "partnerEligibleAmount",
            "promoTotal",
            "payoutStatus",
            "baseIncentiveType",
            "basePercentage",
            "baseApplyTo",
            "baseAmount",
            "promos",
            "aag",
            "extension",
            "partnerIncentiveGroup",
            "transitionPath",
            "purchaseType",
            "rtmMaterial",
            "strategicProgramsPromos",
            "quoteLineItemID",
            "billingFrequency",
            "annualContractValue",
            "totalContractValue"
        })
        public static class PayoutLineItem {

            @XmlElement(name = "OrderLine_ID")
            protected String orderLineID;
            @XmlElement(name = "SKU_Marketing")
            protected String skuMarketing;
            @XmlElement(name = "Product_Line_ID")
            protected String productLineID;
            @XmlElement(name = "Edition")
            protected String edition;
            @XmlElement(name = "SRP_USD")
            protected BigDecimal srpusd;
            @XmlElement(name = "Quantity")
            protected Integer quantity;
            @XmlElement(name = "Discount_Upfront")
            protected BigDecimal discountUpfront;
            @XmlElement(name = "Discount_Program")
            protected BigDecimal discountProgram;
            @XmlElement(name = "Discount_Channel")
            protected BigDecimal discountChannel;
            @XmlElement(name = "Discount_Exception")
            protected BigDecimal discountException;
            @XmlElement(name = "Surcharge_Customer")
            protected BigDecimal surchargeCustomer;
            @XmlElement(name = "Discount_Upfront_Amount")
            protected BigDecimal discountUpfrontAmount;
            @XmlElement(name = "Discount_Program_Amount")
            protected BigDecimal discountProgramAmount;
            @XmlElement(name = "Discount_Channel_Amount")
            protected BigDecimal discountChannelAmount;
            @XmlElement(name = "Discount_Exception_Amount")
            protected BigDecimal discountExceptionAmount;
            @XmlElement(name = "Surcharge_Customer_Amount")
            protected BigDecimal surchargeCustomerAmount;
            @XmlElement(name = "Partner_Incentive_Eligible_Flag")
            protected Boolean partnerIncentiveEligibleFlag;
            @XmlElement(name = "Partner_Eligible")
            protected Boolean partnerEligible;
            @XmlElement(name = "Partner_Eligible_Amount")
            protected BigDecimal partnerEligibleAmount;
            @XmlElement(name = "Promo_Total")
            protected BigDecimal promoTotal;
            @XmlElement(name = "Payout_Status")
            protected String payoutStatus;
            @XmlElement(name = "Base_Incentive_Type")
            protected String baseIncentiveType;
            @XmlElement(name = "Base_Percentage")
            protected BigDecimal basePercentage;
            @XmlElement(name = "Base_ApplyTo")
            protected String baseApplyTo;
            @XmlElement(name = "Base_Amount")
            protected BigDecimal baseAmount;
            @XmlElement(name = "Promos", required = true)
            protected Payout.PayoutLineItems.PayoutLineItem.Promos promos;
            @XmlElement(name = "AAG")
            protected String aag;
            @XmlElement(name = "Extension")
            protected String extension;
            @XmlElement(name = "Partner_Incentive_Group")
            protected String partnerIncentiveGroup;
            @XmlElement(name = "TransitionPath")
            protected String transitionPath;
            @XmlElement(name = "Purchase_Type")
            protected String purchaseType;
            @XmlElement(name = "RTM_Material")
            protected String rtmMaterial;
            @XmlElement(name = "StrategicProgramsPromos")
            protected String strategicProgramsPromos;
            @XmlElement(name = "Quote_Line_Item_ID", required = true)
            protected String quoteLineItemID;
            @XmlElement(name = "Billing_Frequency")
            protected String billingFrequency;
            @XmlElement(name = "Annual_Contract_Value")
            protected BigDecimal annualContractValue;
            @XmlElement(name = "Total_Contract_Value")
            protected BigDecimal totalContractValue;

            /**
             * Gets the value of the orderLineID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrderLineID() {
                return orderLineID;
            }

            /**
             * Sets the value of the orderLineID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrderLineID(String value) {
                this.orderLineID = value;
            }

            /**
             * Gets the value of the skuMarketing property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSKUMarketing() {
                return skuMarketing;
            }

            /**
             * Sets the value of the skuMarketing property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSKUMarketing(String value) {
                this.skuMarketing = value;
            }

            /**
             * Gets the value of the productLineID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProductLineID() {
                return productLineID;
            }

            /**
             * Sets the value of the productLineID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProductLineID(String value) {
                this.productLineID = value;
            }

            /**
             * Gets the value of the edition property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEdition() {
                return edition;
            }

            /**
             * Sets the value of the edition property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEdition(String value) {
                this.edition = value;
            }

            /**
             * Gets the value of the srpusd property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getSRPUSD() {
                return srpusd;
            }

            /**
             * Sets the value of the srpusd property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setSRPUSD(BigDecimal value) {
                this.srpusd = value;
            }

            /**
             * Gets the value of the quantity property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getQuantity() {
                return quantity;
            }

            /**
             * Sets the value of the quantity property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setQuantity(Integer value) {
                this.quantity = value;
            }

            /**
             * Gets the value of the discountUpfront property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getDiscountUpfront() {
                return discountUpfront;
            }

            /**
             * Sets the value of the discountUpfront property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setDiscountUpfront(BigDecimal value) {
                this.discountUpfront = value;
            }

            /**
             * Gets the value of the discountProgram property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getDiscountProgram() {
                return discountProgram;
            }

            /**
             * Sets the value of the discountProgram property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setDiscountProgram(BigDecimal value) {
                this.discountProgram = value;
            }

            /**
             * Gets the value of the discountChannel property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getDiscountChannel() {
                return discountChannel;
            }

            /**
             * Sets the value of the discountChannel property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setDiscountChannel(BigDecimal value) {
                this.discountChannel = value;
            }

            /**
             * Gets the value of the discountException property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getDiscountException() {
                return discountException;
            }

            /**
             * Sets the value of the discountException property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setDiscountException(BigDecimal value) {
                this.discountException = value;
            }

            /**
             * Gets the value of the surchargeCustomer property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getSurchargeCustomer() {
                return surchargeCustomer;
            }

            /**
             * Sets the value of the surchargeCustomer property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setSurchargeCustomer(BigDecimal value) {
                this.surchargeCustomer = value;
            }

            /**
             * Gets the value of the discountUpfrontAmount property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getDiscountUpfrontAmount() {
                return discountUpfrontAmount;
            }

            /**
             * Sets the value of the discountUpfrontAmount property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setDiscountUpfrontAmount(BigDecimal value) {
                this.discountUpfrontAmount = value;
            }

            /**
             * Gets the value of the discountProgramAmount property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getDiscountProgramAmount() {
                return discountProgramAmount;
            }

            /**
             * Sets the value of the discountProgramAmount property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setDiscountProgramAmount(BigDecimal value) {
                this.discountProgramAmount = value;
            }

            /**
             * Gets the value of the discountChannelAmount property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getDiscountChannelAmount() {
                return discountChannelAmount;
            }

            /**
             * Sets the value of the discountChannelAmount property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setDiscountChannelAmount(BigDecimal value) {
                this.discountChannelAmount = value;
            }

            /**
             * Gets the value of the discountExceptionAmount property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getDiscountExceptionAmount() {
                return discountExceptionAmount;
            }

            /**
             * Sets the value of the discountExceptionAmount property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setDiscountExceptionAmount(BigDecimal value) {
                this.discountExceptionAmount = value;
            }

            /**
             * Gets the value of the surchargeCustomerAmount property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getSurchargeCustomerAmount() {
                return surchargeCustomerAmount;
            }

            /**
             * Sets the value of the surchargeCustomerAmount property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setSurchargeCustomerAmount(BigDecimal value) {
                this.surchargeCustomerAmount = value;
            }

            /**
             * Gets the value of the partnerIncentiveEligibleFlag property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isPartnerIncentiveEligibleFlag() {
                return partnerIncentiveEligibleFlag;
            }

            /**
             * Sets the value of the partnerIncentiveEligibleFlag property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setPartnerIncentiveEligibleFlag(Boolean value) {
                this.partnerIncentiveEligibleFlag = value;
            }

            /**
             * Gets the value of the partnerEligible property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isPartnerEligible() {
                return partnerEligible;
            }

            /**
             * Sets the value of the partnerEligible property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setPartnerEligible(Boolean value) {
                this.partnerEligible = value;
            }

            /**
             * Gets the value of the partnerEligibleAmount property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPartnerEligibleAmount() {
                return partnerEligibleAmount;
            }

            /**
             * Sets the value of the partnerEligibleAmount property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setPartnerEligibleAmount(BigDecimal value) {
                this.partnerEligibleAmount = value;
            }

            /**
             * Gets the value of the promoTotal property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPromoTotal() {
                return promoTotal;
            }

            /**
             * Sets the value of the promoTotal property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setPromoTotal(BigDecimal value) {
                this.promoTotal = value;
            }

            /**
             * Gets the value of the payoutStatus property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPayoutStatus() {
                return payoutStatus;
            }

            /**
             * Sets the value of the payoutStatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPayoutStatus(String value) {
                this.payoutStatus = value;
            }

            /**
             * Gets the value of the baseIncentiveType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBaseIncentiveType() {
                return baseIncentiveType;
            }

            /**
             * Sets the value of the baseIncentiveType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBaseIncentiveType(String value) {
                this.baseIncentiveType = value;
            }

            /**
             * Gets the value of the basePercentage property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getBasePercentage() {
                return basePercentage;
            }

            /**
             * Sets the value of the basePercentage property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setBasePercentage(BigDecimal value) {
                this.basePercentage = value;
            }

            /**
             * Gets the value of the baseApplyTo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBaseApplyTo() {
                return baseApplyTo;
            }

            /**
             * Sets the value of the baseApplyTo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBaseApplyTo(String value) {
                this.baseApplyTo = value;
            }

            /**
             * Gets the value of the baseAmount property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getBaseAmount() {
                return baseAmount;
            }

            /**
             * Sets the value of the baseAmount property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setBaseAmount(BigDecimal value) {
                this.baseAmount = value;
            }

            /**
             * Gets the value of the promos property.
             * 
             * @return
             *     possible object is
             *     {@link Payout.PayoutLineItems.PayoutLineItem.Promos }
             *     
             */
            public Payout.PayoutLineItems.PayoutLineItem.Promos getPromos() {
                return promos;
            }

            /**
             * Sets the value of the promos property.
             * 
             * @param value
             *     allowed object is
             *     {@link Payout.PayoutLineItems.PayoutLineItem.Promos }
             *     
             */
            public void setPromos(Payout.PayoutLineItems.PayoutLineItem.Promos value) {
                this.promos = value;
            }

            /**
             * Gets the value of the aag property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAAG() {
                return aag;
            }

            /**
             * Sets the value of the aag property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAAG(String value) {
                this.aag = value;
            }

            /**
             * Gets the value of the extension property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExtension() {
                return extension;
            }

            /**
             * Sets the value of the extension property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExtension(String value) {
                this.extension = value;
            }

            /**
             * Gets the value of the partnerIncentiveGroup property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPartnerIncentiveGroup() {
                return partnerIncentiveGroup;
            }

            /**
             * Sets the value of the partnerIncentiveGroup property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPartnerIncentiveGroup(String value) {
                this.partnerIncentiveGroup = value;
            }

            /**
             * Gets the value of the transitionPath property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTransitionPath() {
                return transitionPath;
            }

            /**
             * Sets the value of the transitionPath property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTransitionPath(String value) {
                this.transitionPath = value;
            }

            /**
             * Gets the value of the purchaseType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPurchaseType() {
                return purchaseType;
            }

            /**
             * Sets the value of the purchaseType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPurchaseType(String value) {
                this.purchaseType = value;
            }

            /**
             * Gets the value of the rtmMaterial property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRTMMaterial() {
                return rtmMaterial;
            }

            /**
             * Sets the value of the rtmMaterial property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRTMMaterial(String value) {
                this.rtmMaterial = value;
            }

            /**
             * Gets the value of the strategicProgramsPromos property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStrategicProgramsPromos() {
                return strategicProgramsPromos;
            }

            /**
             * Sets the value of the strategicProgramsPromos property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStrategicProgramsPromos(String value) {
                this.strategicProgramsPromos = value;
            }

            /**
             * Gets the value of the quoteLineItemID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getQuoteLineItemID() {
                return quoteLineItemID;
            }

            /**
             * Sets the value of the quoteLineItemID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setQuoteLineItemID(String value) {
                this.quoteLineItemID = value;
            }

            /**
             * Gets the value of the billingFrequency property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBillingFrequency() {
                return billingFrequency;
            }

            /**
             * Sets the value of the billingFrequency property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBillingFrequency(String value) {
                this.billingFrequency = value;
            }

            /**
             * Gets the value of the annualContractValue property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getAnnualContractValue() {
                return annualContractValue;
            }

            /**
             * Sets the value of the annualContractValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setAnnualContractValue(BigDecimal value) {
                this.annualContractValue = value;
            }

            /**
             * Gets the value of the totalContractValue property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getTotalContractValue() {
                return totalContractValue;
            }

            /**
             * Sets the value of the totalContractValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setTotalContractValue(BigDecimal value) {
                this.totalContractValue = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Promo" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Number" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                   &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="Percentage" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
             *                   &lt;element name="ApplyTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "promo"
            })
            public static class Promos {

                @XmlElement(name = "Promo")
                protected List<Payout.PayoutLineItems.PayoutLineItem.Promos.Promo> promo;

                /**
                 * Gets the value of the promo property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the promo property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getPromo().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Payout.PayoutLineItems.PayoutLineItem.Promos.Promo }
                 * 
                 * 
                 */
                public List<Payout.PayoutLineItems.PayoutLineItem.Promos.Promo> getPromo() {
                    if (promo == null) {
                        promo = new ArrayList<Payout.PayoutLineItems.PayoutLineItem.Promos.Promo>();
                    }
                    return this.promo;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Number" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="Percentage" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
                 *         &lt;element name="ApplyTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "number",
                    "type",
                    "percentage",
                    "applyTo",
                    "amount"
                })
                public static class Promo {

                    @XmlElement(name = "Number")
                    protected int number;
                    @XmlElement(name = "Type", required = true)
                    protected String type;
                    @XmlElement(name = "Percentage", required = true)
                    protected BigDecimal percentage;
                    @XmlElement(name = "ApplyTo", required = true)
                    protected String applyTo;
                    @XmlElement(name = "Amount", required = true)
                    protected BigDecimal amount;

                    /**
                     * Gets the value of the number property.
                     * 
                     */
                    public int getNumber() {
                        return number;
                    }

                    /**
                     * Sets the value of the number property.
                     * 
                     */
                    public void setNumber(int value) {
                        this.number = value;
                    }

                    /**
                     * Gets the value of the type property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getType() {
                        return type;
                    }

                    /**
                     * Sets the value of the type property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setType(String value) {
                        this.type = value;
                    }

                    /**
                     * Gets the value of the percentage property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getPercentage() {
                        return percentage;
                    }

                    /**
                     * Sets the value of the percentage property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setPercentage(BigDecimal value) {
                        this.percentage = value;
                    }

                    /**
                     * Gets the value of the applyTo property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getApplyTo() {
                        return applyTo;
                    }

                    /**
                     * Sets the value of the applyTo property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setApplyTo(String value) {
                        this.applyTo = value;
                    }

                    /**
                     * Gets the value of the amount property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getAmount() {
                        return amount;
                    }

                    /**
                     * Sets the value of the amount property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setAmount(BigDecimal value) {
                        this.amount = value;
                    }

                }

            }

        }

    }

}
