//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.16 at 09:44:55 AM EDT 
//


package citrite;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:schemas-citrite-net:pip:sfdc:order:1}Order"/>
 *         &lt;element ref="{urn:schemas-citrite-net:pip:sfdc:registration:1}RewardRegistration"/>
 *         &lt;element ref="{urn:schemas-citrite-net:pip:sfdc:partnerInfo:1}PartnerInfo" minOccurs="0"/>
 *         &lt;element ref="{urn:schemas-citrite-net:pip:sfdc:partnerfunctions:1}PartnerFunctions"/>
 *         &lt;element ref="{urn:schemas-citrite-net:pip:sfdc:originalorder:1}OriginalOrder" minOccurs="0"/>
 *         &lt;element ref="{urn:schemas-citrite-net:pip:salesforce:salesexception:1}SalesExceptions" minOccurs="0"/>
 *         &lt;element ref="{urn:schemas-citrite-net:pip:salesforce:product-authorization:1}ProductAuthorizations" minOccurs="0"/>
 *         &lt;element ref="{urn:schemas-citrite-net:pip:sfdc:enduser:1}EndUserInfo"/>
 *         &lt;element ref="{urn:schemas-citrite-net:pip:salesforce:specialization:1}Specializations"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "order",
    "rewardRegistration",
    "partnerInfo",
    "partnerFunctions",
    "originalOrder",
    "salesExceptions",
    "productAuthorizations",
    "endUserInfo",
    "specializations"
})
public class Request {

    @XmlElement(name = "Order", namespace = "urn:schemas-citrite-net:pip:sfdc:order:1", required = true, nillable = true)
    protected Order order;
    @XmlElement(name = "RewardRegistration", namespace = "urn:schemas-citrite-net:pip:sfdc:registration:1", required = true)
    protected RewardRegistration rewardRegistration;
    @XmlElement(name = "PartnerInfo", namespace = "urn:schemas-citrite-net:pip:sfdc:partnerInfo:1")
    protected PartnerInfo partnerInfo;
    @XmlElement(name = "PartnerFunctions", namespace = "urn:schemas-citrite-net:pip:sfdc:partnerfunctions:1", required = true)
    protected PartnerFunctions partnerFunctions;
    @XmlElement(name = "OriginalOrder", namespace = "urn:schemas-citrite-net:pip:sfdc:originalorder:1")
    protected OriginalOrder originalOrder;
    @XmlElement(name = "SalesExceptions", namespace = "urn:schemas-citrite-net:pip:salesforce:salesexception:1")
    protected SalesExceptions salesExceptions;
    @XmlElement(name = "ProductAuthorizations", namespace = "urn:schemas-citrite-net:pip:salesforce:product-authorization:1")
    protected ProductAuthorizations productAuthorizations;
    @XmlElement(name = "EndUserInfo", namespace = "urn:schemas-citrite-net:pip:sfdc:enduser:1", required = true, nillable = true)
    protected EndUserInfo endUserInfo;
    @XmlElement(name = "Specializations", namespace = "urn:schemas-citrite-net:pip:salesforce:specialization:1", required = true)
    protected Specializations specializations;

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link Order }
     *     
     */
    public Order getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link Order }
     *     
     */
    public void setOrder(Order value) {
        this.order = value;
    }

    /**
     * Gets the value of the rewardRegistration property.
     * 
     * @return
     *     possible object is
     *     {@link RewardRegistration }
     *     
     */
    public RewardRegistration getRewardRegistration() {
        return rewardRegistration;
    }

    /**
     * Sets the value of the rewardRegistration property.
     * 
     * @param value
     *     allowed object is
     *     {@link RewardRegistration }
     *     
     */
    public void setRewardRegistration(RewardRegistration value) {
        this.rewardRegistration = value;
    }

    /**
     * Gets the value of the partnerInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PartnerInfo }
     *     
     */
    public PartnerInfo getPartnerInfo() {
        return partnerInfo;
    }

    /**
     * Sets the value of the partnerInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartnerInfo }
     *     
     */
    public void setPartnerInfo(PartnerInfo value) {
        this.partnerInfo = value;
    }

    /**
     * Gets the value of the partnerFunctions property.
     * 
     * @return
     *     possible object is
     *     {@link PartnerFunctions }
     *     
     */
    public PartnerFunctions getPartnerFunctions() {
        return partnerFunctions;
    }

    /**
     * Sets the value of the partnerFunctions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartnerFunctions }
     *     
     */
    public void setPartnerFunctions(PartnerFunctions value) {
        this.partnerFunctions = value;
    }

    /**
     * Gets the value of the originalOrder property.
     * 
     * @return
     *     possible object is
     *     {@link OriginalOrder }
     *     
     */
    public OriginalOrder getOriginalOrder() {
        return originalOrder;
    }

    /**
     * Sets the value of the originalOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginalOrder }
     *     
     */
    public void setOriginalOrder(OriginalOrder value) {
        this.originalOrder = value;
    }

    /**
     * Gets the value of the salesExceptions property.
     * 
     * @return
     *     possible object is
     *     {@link SalesExceptions }
     *     
     */
    public SalesExceptions getSalesExceptions() {
        return salesExceptions;
    }

    /**
     * Sets the value of the salesExceptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesExceptions }
     *     
     */
    public void setSalesExceptions(SalesExceptions value) {
        this.salesExceptions = value;
    }

    /**
     * Gets the value of the productAuthorizations property.
     * 
     * @return
     *     possible object is
     *     {@link ProductAuthorizations }
     *     
     */
    public ProductAuthorizations getProductAuthorizations() {
        return productAuthorizations;
    }

    /**
     * Sets the value of the productAuthorizations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductAuthorizations }
     *     
     */
    public void setProductAuthorizations(ProductAuthorizations value) {
        this.productAuthorizations = value;
    }

    /**
     * Gets the value of the endUserInfo property.
     * 
     * @return
     *     possible object is
     *     {@link EndUserInfo }
     *     
     */
    public EndUserInfo getEndUserInfo() {
        return endUserInfo;
    }

    /**
     * Sets the value of the endUserInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndUserInfo }
     *     
     */
    public void setEndUserInfo(EndUserInfo value) {
        this.endUserInfo = value;
    }

    /**
     * Gets the value of the specializations property.
     * 
     * @return
     *     possible object is
     *     {@link Specializations }
     *     
     */
    public Specializations getSpecializations() {
        return specializations;
    }

    /**
     * Sets the value of the specializations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Specializations }
     *     
     */
    public void setSpecializations(Specializations value) {
        this.specializations = value;
    }

}
