//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.16 at 09:44:55 AM EDT 
//


package citrite;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="SalesException" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SE_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="SE_Sub_Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="SE_Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="SE_Expiration_Date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "salesException"
})
@XmlRootElement(name = "SalesExceptions")
public class SalesExceptions {

    @XmlElement(name = "SalesException")
    protected List<SalesExceptions.SalesException> salesException;

    /**
     * Gets the value of the salesException property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the salesException property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSalesException().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SalesExceptions.SalesException }
     * 
     * 
     */
    public List<SalesExceptions.SalesException> getSalesException() {
        if (salesException == null) {
            salesException = new ArrayList<SalesExceptions.SalesException>();
        }
        return this.salesException;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SE_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="SE_Sub_Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="SE_Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="SE_Expiration_Date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "seid",
        "seSubType",
        "seStatus",
        "seExpirationDate"
    })
    public static class SalesException {

        @XmlElement(name = "SE_ID")
        protected String seid;
        @XmlElement(name = "SE_Sub_Type")
        protected String seSubType;
        @XmlElement(name = "SE_Status")
        protected String seStatus;
        @XmlElement(name = "SE_Expiration_Date")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar seExpirationDate;

        /**
         * Gets the value of the seid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSEID() {
            return seid;
        }

        /**
         * Sets the value of the seid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSEID(String value) {
            this.seid = value;
        }

        /**
         * Gets the value of the seSubType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSESubType() {
            return seSubType;
        }

        /**
         * Sets the value of the seSubType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSESubType(String value) {
            this.seSubType = value;
        }

        /**
         * Gets the value of the seStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSEStatus() {
            return seStatus;
        }

        /**
         * Sets the value of the seStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSEStatus(String value) {
            this.seStatus = value;
        }

        /**
         * Gets the value of the seExpirationDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getSEExpirationDate() {
            return seExpirationDate;
        }

        /**
         * Sets the value of the seExpirationDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setSEExpirationDate(XMLGregorianCalendar value) {
            this.seExpirationDate = value;
        }

    }

}
